# Site settings
title: Samuel Reichert
email: samuelreichertt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor Web
baseurl: "" # the subpath of your site, e.g. /blog/
url: "samuelreichert.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
